// <auto-generated />
using GisBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GISBackend.Migrations
{
    [DbContext(typeof(GisDbContext))]
    [Migration("20251130154831_AddPCodeColumn")]
    partial class AddPCodeColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("GisBackend.Models.DivisionInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Density")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Literacy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Population")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DivisionInfos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Area = "13,225 km²",
                            Density = "688 /km²",
                            Literacy = "77.6%",
                            Name = "Barishal",
                            PCode = 10,
                            Population = "9,100,102"
                        },
                        new
                        {
                            Id = 2,
                            Area = "33,909 km²",
                            Density = "979 /km²",
                            Literacy = "78.4%",
                            Name = "Chattogram",
                            PCode = 20,
                            Population = "33,202,326"
                        },
                        new
                        {
                            Id = 3,
                            Area = "20,509 km²",
                            Density = "2,156 /km²",
                            Literacy = "83.6%",
                            Name = "Dhaka",
                            PCode = 30,
                            Population = "44,215,107"
                        },
                        new
                        {
                            Id = 4,
                            Area = "22,284 km²",
                            Density = "782 /km²",
                            Literacy = "76.8%",
                            Name = "Khulna",
                            PCode = 40,
                            Population = "17,416,645"
                        },
                        new
                        {
                            Id = 5,
                            Area = "10,485 km²",
                            Density = "1,146 /km²",
                            Literacy = "67.1%",
                            Name = "Mymensingh",
                            PCode = 45,
                            Population = "12,225,498"
                        },
                        new
                        {
                            Id = 6,
                            Area = "18,153 km²",
                            Density = "1,121 /km²",
                            Literacy = "73.2%",
                            Name = "Rajshahi",
                            PCode = 50,
                            Population = "20,353,119"
                        },
                        new
                        {
                            Id = 7,
                            Area = "16,185 km²",
                            Density = "1,088 /km²",
                            Literacy = "70.8%",
                            Name = "Rangpur",
                            PCode = 55,
                            Population = "17,610,956"
                        },
                        new
                        {
                            Id = 8,
                            Area = "12,635 km²",
                            Density = "873 /km²",
                            Literacy = "76.0%",
                            Name = "Sylhet",
                            PCode = 60,
                            Population = "11,034,863"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
